export const users = [
    {
      id: "admin1",
      fullName: "Sheldon Jacob Colin",
      email: "admin1@admin.com",
      password: "adminpass",
      phoneNumber: "9876543210",
      role: "admin",
      designation: "Hospital Manager",
      accessLevel: "Super Admin",
      dateOfJoining: "2020-05-15",
      address: "123 Admin Street, City, Country",
    },
    {
      id: "doctor1",
      fullName: "Dr. Sarah Smith",
      email: "doctor1@doctor.com",
      password: "doctorpass",
      phoneNumber: "9123456789",
      role: "doctor",
      specialization: "Cardiologist",
      experience: 10,
      medicalLicenseNumber: "DOC123456",
      availabilitySchedule: "Mon-Fri: 9 AM - 3 PM",
      consultationFee: "$100",
      address: "45 Doctor Lane, City, Country",
    },
    {
      id: "patient1",
      fullName: "Alice Johnson",
      email: "patient1@example.com",
      password: "patientpass",
      phoneNumber: "9871234560",
      role: "patient",
      age: 30,
      gender: "Female",
      bloodGroup: "O+",
      medicalHistory: ["Diabetes", "Hypertension"],
      currentMedications: ["Metformin", "Lisinopril"],
      allergies: ["Penicillin"],
      doctorAssigned: "Dr. Sarah Smith",
      nextAppointmentDate: "2025-04-10",
      emergencyContact: { name: "Bob Johnson", phone: "9876543212" },
      address: "78 Patient Road, City, Country",
    },
  ];
  